# Generated by Django 5.0.3 on 2024-04-18 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_mecanico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'ordering': ['nome'], 'verbose_name': 'oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.RenameField(
            model_name='mecanico',
            old_name='usuario',
            new_name='oficina',
        ),
        migrations.AlterField(
            model_name='oficina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
