# Generated by Django 5.0.3 on 2024-04-22 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0003_alter_oficina_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'ordering': ['nome'], 'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterField(
            model_name='oficina',
            name='email',
            field=models.CharField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
