# Generated by Django 5.0.3 on 2024-04-22 21:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0004_alter_oficina_options_alter_oficina_email_and_more'),
        ('servicos', '0003_ordemservico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['data_entrada'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Servico', 'verbose_name_plural': 'Servicos'},
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='mecanico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geral.mecanico', verbose_name='Mecanico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='placa',
            field=models.CharField(help_text='Ex: BRA-2145', max_length=8, verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='previsao',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Previsão'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.CharField(help_text='Ex: Honda Fan 160', max_length=100, verbose_name='Veiculo'),
        ),
    ]
